---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
data:
  MINIO_ACCESS_KEY: bXktYWNjZXNzLWtleQ==
  MINIO_SECRET_KEY: bXlYWFh4eHgvc2VjcmV0WFhYWHh4eC9rZXlYWHh4eA==
