---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: minio
  name: minio
  labels:
    app: minio

spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - hdd
      containers:
        - name: minio
          image: minio/minio:RELEASE.2020-10-28T08-16-50Z-arm64
          args: ['server', '/data']
          ports:
            - name: minio
              containerPort: 9000
          volumeMounts:
            - name: s3-pv-storage
              mountPath: /data
          env:
            - name: MINIO_IDENTITY_OPENID_CONFIG_URL
              value: https://keycloak.example.com/auth/realms/home/.well-known/openid-configuration
            - name: MINIO_IDENTITY_OPENID_CLIENT_ID
              value: minio
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_SECRET_KEY
      volumes:
        - name: s3-pv-storage
          persistentVolumeClaim:
            claimName: s3-pvc
